!SESSION 2017-12-24 23:10:17.505 -----------------------------------------------
eclipse.buildId=4.5.2.M20160212-1500
java.version=1.8.0_151
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86 -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -data D:\code\java -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.jface 2 0 2017-12-24 23:10:21.013
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2017-12-24 23:10:21.013
!MESSAGE A conflict occurred for ALT+CTRL+T:
Binding(ALT+CTRL+T,
	ParameterizedCommand(Command(org.eclipse.tm.terminal.connector.local.command.launch,Open Local Terminal on Selection,
		,
		Category(org.eclipse.tm.terminal.view.ui.commands.category,Terminal Commands,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@5bb37d,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(ALT+CTRL+T,
	ParameterizedCommand(Command(org.eclipse.team.svn.ui.command.EditPropertiesCommand,Show Properties,
		,
		Category(org.eclipse.team.svn.ui.command.category,SVN,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@18575fe,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)

!ENTRY org.eclipse.egit.ui 2 0 2017-12-24 23:10:28.410
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\TrungNT'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.eclipse.egit.core 4 0 2017-12-24 23:23:39.840
!MESSAGE An exception occurred during push on URI https://github.com/nguyentrantrung986/java.git: An internal Exception occurred during push: Source ref refs/heads/master doesn't resolve to any object.
!STACK 0
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of push command
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:182)
	at org.eclipse.egit.core.op.PushOperation.run(PushOperation.java:228)
	at org.eclipse.egit.ui.internal.push.PushOperationUI.execute(PushOperationUI.java:167)
	at org.eclipse.egit.ui.internal.push.PushOperationUI$1.run(PushOperationUI.java:229)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Source ref refs/heads/master doesn't resolve to any object.
	at org.eclipse.jgit.transport.RemoteRefUpdate.<init>(RemoteRefUpdate.java:288)
	at org.eclipse.jgit.transport.RemoteRefUpdate.<init>(RemoteRefUpdate.java:192)
	at org.eclipse.jgit.transport.Transport.findRemoteRefUpdatesFor(Transport.java:646)
	at org.eclipse.jgit.transport.Transport.findRemoteRefUpdatesFor(Transport.java:1269)
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:153)
	... 4 more

!ENTRY org.eclipse.equinox.security 1 0 2017-12-24 23:24:30.511
!MESSAGE New keyring password generated. 

!ENTRY org.eclipse.egit.core 4 0 2017-12-24 23:25:11.831
!MESSAGE An exception occurred during push on URI https://github.com/nguyentrantrung986/java.git: An internal Exception occurred during push: Source ref HEAD doesn't resolve to any object.
!STACK 0
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of push command
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:182)
	at org.eclipse.egit.core.op.PushOperation.run(PushOperation.java:228)
	at org.eclipse.egit.ui.internal.push.PushOperationUI.execute(PushOperationUI.java:167)
	at org.eclipse.egit.ui.internal.push.PushOperationUI$1.run(PushOperationUI.java:229)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Source ref HEAD doesn't resolve to any object.
	at org.eclipse.jgit.transport.RemoteRefUpdate.<init>(RemoteRefUpdate.java:288)
	at org.eclipse.jgit.transport.RemoteRefUpdate.<init>(RemoteRefUpdate.java:192)
	at org.eclipse.jgit.transport.Transport.findRemoteRefUpdatesFor(Transport.java:646)
	at org.eclipse.jgit.transport.Transport.findRemoteRefUpdatesFor(Transport.java:1269)
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:153)
	... 4 more

!ENTRY org.eclipse.egit.core 4 0 2017-12-24 23:25:43.530
!MESSAGE An exception occurred during push on URI https://github.com/nguyentrantrung986/java.git: An internal Exception occurred during push: Source ref HEAD doesn't resolve to any object.
!STACK 0
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of push command
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:182)
	at org.eclipse.egit.core.op.PushOperation.run(PushOperation.java:228)
	at org.eclipse.egit.ui.internal.push.PushOperationUI.execute(PushOperationUI.java:167)
	at org.eclipse.egit.ui.internal.push.PushOperationUI$1.run(PushOperationUI.java:229)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Source ref HEAD doesn't resolve to any object.
	at org.eclipse.jgit.transport.RemoteRefUpdate.<init>(RemoteRefUpdate.java:288)
	at org.eclipse.jgit.transport.RemoteRefUpdate.<init>(RemoteRefUpdate.java:192)
	at org.eclipse.jgit.transport.Transport.findRemoteRefUpdatesFor(Transport.java:646)
	at org.eclipse.jgit.transport.Transport.findRemoteRefUpdatesFor(Transport.java:1269)
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:153)
	... 4 more

!ENTRY org.eclipse.egit.ui 4 0 2017-12-24 23:27:43.916
!MESSAGE Exception caught during execution of add command
!STACK 0
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:211)
	at org.eclipse.egit.core.op.CommitOperation.addUntracked(CommitOperation.java:222)
	at org.eclipse.egit.core.op.CommitOperation.access$4(CommitOperation.java:210)
	at org.eclipse.egit.core.op.CommitOperation$1.run(CommitOperation.java:195)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.egit.core.op.CommitOperation.execute(CommitOperation.java:206)
	at org.eclipse.egit.ui.internal.commit.CommitJob.run(CommitJob.java:98)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: The process cannot access the file because another process has locked a portion of the file
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(Unknown Source)
	at org.eclipse.jgit.util.IO.readFully(IO.java:302)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.insert(ObjectDirectoryInserter.java:103)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:187)
	... 7 more

!ENTRY org.eclipse.egit.ui 4 0 2017-12-24 23:28:17.464
!MESSAGE Exception caught during execution of add command
!STACK 0
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:211)
	at org.eclipse.egit.core.op.CommitOperation.addUntracked(CommitOperation.java:222)
	at org.eclipse.egit.core.op.CommitOperation.access$4(CommitOperation.java:210)
	at org.eclipse.egit.core.op.CommitOperation$1.run(CommitOperation.java:195)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.egit.core.op.CommitOperation.execute(CommitOperation.java:206)
	at org.eclipse.egit.ui.internal.commit.CommitJob.run(CommitJob.java:98)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: The process cannot access the file because another process has locked a portion of the file
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(Unknown Source)
	at org.eclipse.jgit.util.IO.readFully(IO.java:302)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.insert(ObjectDirectoryInserter.java:103)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:187)
	... 7 more

!ENTRY org.eclipse.egit.ui 4 0 2017-12-24 23:31:19.020
!MESSAGE Exception caught during execution of add command
!STACK 0
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:211)
	at org.eclipse.egit.core.op.CommitOperation.addUntracked(CommitOperation.java:222)
	at org.eclipse.egit.core.op.CommitOperation.access$4(CommitOperation.java:210)
	at org.eclipse.egit.core.op.CommitOperation$1.run(CommitOperation.java:195)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.egit.core.op.CommitOperation.execute(CommitOperation.java:206)
	at org.eclipse.egit.ui.internal.commit.CommitJob.run(CommitJob.java:98)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: The process cannot access the file because another process has locked a portion of the file
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(Unknown Source)
	at org.eclipse.jgit.util.IO.readFully(IO.java:302)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.insert(ObjectDirectoryInserter.java:103)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:187)
	... 7 more

!ENTRY org.eclipse.egit.ui 4 0 2017-12-24 23:33:50.503
!MESSAGE Exception caught during execution of add command
!STACK 0
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:211)
	at org.eclipse.egit.core.op.CommitOperation.addUntracked(CommitOperation.java:222)
	at org.eclipse.egit.core.op.CommitOperation.access$4(CommitOperation.java:210)
	at org.eclipse.egit.core.op.CommitOperation$1.run(CommitOperation.java:195)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.egit.core.op.CommitOperation.execute(CommitOperation.java:206)
	at org.eclipse.egit.ui.internal.commit.CommitJob.run(CommitJob.java:98)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: The process cannot access the file because another process has locked a portion of the file
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(Unknown Source)
	at org.eclipse.jgit.util.IO.readFully(IO.java:302)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.insert(ObjectDirectoryInserter.java:103)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:187)
	... 7 more

!ENTRY org.eclipse.egit.ui 4 0 2017-12-24 23:40:10.940
!MESSAGE Exception caught during execution of add command
!STACK 0
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:211)
	at org.eclipse.egit.core.op.CommitOperation.addUntracked(CommitOperation.java:222)
	at org.eclipse.egit.core.op.CommitOperation.access$4(CommitOperation.java:210)
	at org.eclipse.egit.core.op.CommitOperation$1.run(CommitOperation.java:195)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.egit.core.op.CommitOperation.execute(CommitOperation.java:206)
	at org.eclipse.egit.ui.internal.commit.CommitJob.run(CommitJob.java:98)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: The process cannot access the file because another process has locked a portion of the file
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(Unknown Source)
	at org.eclipse.jgit.util.IO.readFully(IO.java:302)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.insert(ObjectDirectoryInserter.java:103)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:187)
	... 7 more

!ENTRY org.eclipse.egit.ui 4 0 2017-12-24 23:41:27.534
!MESSAGE Exception caught during execution of add command
!STACK 0
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:211)
	at org.eclipse.egit.core.op.CommitOperation.addUntracked(CommitOperation.java:222)
	at org.eclipse.egit.core.op.CommitOperation.access$4(CommitOperation.java:210)
	at org.eclipse.egit.core.op.CommitOperation$1.run(CommitOperation.java:195)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.egit.core.op.CommitOperation.execute(CommitOperation.java:206)
	at org.eclipse.egit.ui.internal.commit.CommitJob.run(CommitJob.java:98)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: The process cannot access the file because another process has locked a portion of the file
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(Unknown Source)
	at org.eclipse.jgit.util.IO.readFully(IO.java:302)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.insert(ObjectDirectoryInserter.java:103)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:187)
	... 7 more

!ENTRY org.eclipse.egit.ui 4 0 2017-12-24 23:42:06.170
!MESSAGE Exception caught during execution of add command
!STACK 0
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:211)
	at org.eclipse.egit.core.op.CommitOperation.addUntracked(CommitOperation.java:222)
	at org.eclipse.egit.core.op.CommitOperation.access$4(CommitOperation.java:210)
	at org.eclipse.egit.core.op.CommitOperation$1.run(CommitOperation.java:195)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.egit.core.op.CommitOperation.execute(CommitOperation.java:206)
	at org.eclipse.egit.ui.internal.commit.CommitJob.run(CommitJob.java:98)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: The process cannot access the file because another process has locked a portion of the file
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(Unknown Source)
	at org.eclipse.jgit.util.IO.readFully(IO.java:302)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.insert(ObjectDirectoryInserter.java:103)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:187)
	... 7 more

!ENTRY org.eclipse.egit.ui 4 0 2017-12-24 23:42:44.021
!MESSAGE Exception caught during execution of add command
!STACK 0
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:211)
	at org.eclipse.egit.core.op.CommitOperation.addUntracked(CommitOperation.java:222)
	at org.eclipse.egit.core.op.CommitOperation.access$4(CommitOperation.java:210)
	at org.eclipse.egit.core.op.CommitOperation$1.run(CommitOperation.java:195)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.egit.core.op.CommitOperation.execute(CommitOperation.java:206)
	at org.eclipse.egit.ui.internal.commit.CommitJob.run(CommitJob.java:98)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: The process cannot access the file because another process has locked a portion of the file
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(Unknown Source)
	at org.eclipse.jgit.util.IO.readFully(IO.java:302)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.insert(ObjectDirectoryInserter.java:103)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:187)
	... 7 more
